version: "3.8"

services:
  database_service:
    container_name: database_container
    image: postgres:16.3-alpine3.20
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"

  auth_service:
    container_name: auth_container
    build: .
    env_file:
      - .env
    depends_on:
      - database_service
    command: sh -c "sleep 10 && alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 7777"
    ports:
      - "7777:7777"
